[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["cd acme-training-website && npm ci --cache .npm --prefer-offline"]

[phases.build]
cmds = ["cd acme-training-website && npm run build"]

[start]
cmd = "cd acme-training-website && npm start"
