[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd acme-training-website && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd acme-training-website && npx prisma generate", "cd acme-training-website && npm run build"]

[start]
cmd = "cd acme-training-website && npm start"
